---
- name: Find IBM Cloud Log Routing Tenants in Specific Regions
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Set conditional variable from environment
      set_fact:
        ibmcloud_api_key: "{{ lookup('env', 'ibmcloud_api_key') }}"
        tenant_region: "{{ lookup('env', 'tenant_region') | default('') }}"
        target_service_name: "logs-router"
        
    - name: Log in to IBM Cloud
      ansible.builtin.shell: |
        ibmcloud login --apikey "{{ ibmcloud_api_key }}" --no-region -q >/dev/null 2>&1
      register: ibmcloud_login_result
      changed_when: false
      failed_when: ibmcloud_login_result.rc != 0 or 'FAILED' in ibmcloud_login_result.stderr or 'Error' in ibmcloud_login_result.stderr

    - name: Display IBM Cloud login success message
      ansible.builtin.debug:
        msg: "Authentication successful."
      when: ibmcloud_login_result.rc == 0

    - name: Get IAM token for API calls
      ansible.builtin.shell: |
        ibmcloud iam oauth-tokens --output JSON | jq -r '.iam_token'
      register: iam_token_result
      changed_when: false
      failed_when: iam_token_result.rc != 0

    - name: Parse regions from environment variable (older Ansible)
      set_fact:
        regions_list: "{{ ('[' + tenant_region | replace('[', '') | replace(']', '') | replace('\"', '') + ']') | from_yaml }}"
    
    - name: Fail if no valid regions are found
      ansible.builtin.fail:
        msg: "No valid regions found in 'tenant_region'. Exiting."
      when: regions_list | length == 0

    - name: Loop through each region and find log routing tenants
      ansible.builtin.uri:
        url: "https://management.{{ item }}.logs-router.cloud.ibm.com/v1/tenants"
        method: GET
        headers:
          Authorization: "{{ iam_token_result.stdout }}"
          IBM-API-Version: 2025-08-06
        return_content: true
        validate_certs: true
      register: api_response
      loop: "{{ regions_list }}"
      loop_control:
        loop_var: item
      ignore_errors: true
      
    - name: Process and display findings
      ansible.builtin.debug:
        msg: |
          Processing results for region: {{ item.item }}
          Status: {{ item.status }}
          Found tenants: {{ (item.json.tenants | length) if item.status == 200 and item.json.tenants is defined else 0 }}
      loop: "{{ api_response.results }}"
      loop_control:
        loop_var: item
