---
- name: Find IBM Cloud Log Routing Tenants in Specific Regions
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # Use Ansible's `lookup` to get the API key and regions from environment variables
    ibmcloud_api_key: "{{ lookup('env', 'ibmcloud_api_key') }}"
    tenant_region: "{{ lookup('env', 'tenant_region') | default('') }}"
    target_service_name: "logs-router"

  tasks:
    - name: Log in to IBM Cloud
      ansible.builtin.shell: |
        ibmcloud login --apikey "{{ ibmcloud_api_key }}" --no-region -q >/dev/null 2>&1
      register: ibmcloud_login_result
      changed_when: false
      failed_when: ibmcloud_login_result.rc != 0 or
                   'FAILED' in ibmcloud_login_result.stderr or
                   'Error' in ibmcloud_login_result.stderr

    - name: Display IBM Cloud login success message
      ansible.builtin.debug:
        msg: "Authentication successful."
      when: ibmcloud_login_result.rc == 0

    - name: Get IAM token for API calls
      ansible.builtin.shell: |
        ibmcloud iam oauth-tokens --output JSON | jq -r '.iam_token'
      register: iam_token_result
      changed_when: false
      failed_when: iam_token_result.rc != 0

    - name: Parse regions from environment variable
      set_fact:
        regions_list: "{{ tenant_region | replace('[', '') | replace(']', '') | replace('\"', '') | split(',') }}"
    
    - name: Fail if no valid regions are found
      ansible.builtin.fail:
        msg: "No valid regions found in 'tenant_region'. Exiting."
      when: regions_list | length == 0

    - name: Loop through each region and find log routing tenants
      ansible.builtin.uri:
        url: "https://management.{{ item }}.logs-router.cloud.ibm.com/v1/tenants"
        method: GET
        headers:
          Authorization: "{{ iam_token_result.stdout }}"
          IBM-API-Version: 2025-08-06
        return_content: true
        validate_certs: true
      register: api_response
      loop: "{{ regions_list }}"
      loop_control:
        loop_var: item
      ignore_errors: true

    - name: Check and display API results
      ansible.builtin.debug:
        msg: "{{ item.content | from_json | json_query(query) }}"
      vars:
        query: "tenants[?contains(crn, '{{ target_service_name }}') && contains(crn, '{{ item.item }}') && state=='active'].{Name: name, ID: id, Region: '{{ item.item }}', CRN: crn}"
      when: 
        - item.status == 200
        - item.content | length > 0
        - (item.content | from_json).tenants is defined
        - (item.content | from_json).tenants | length > 0
      loop: "{{ api_response.results }}"
      loop_control:
        loop_var: item
    
    - name: Display message for regions with no tenants
      ansible.builtin.debug:
        msg: "No log routing tenants found in region '{{ item.item }}'."
      when: 
        - item.status == 200
        - (item.content | from_json).tenants is defined
        - (item.content | from_json).tenants | length == 0
      loop: "{{ api_response.results }}"
      loop_control:
        loop_var: item

    - name: Display an error message if the API call failed
      ansible.builtin.debug:
        msg: "API call for region '{{ item.item }}' failed. Status code: {{ item.status }}. Error: {{ item.json.error_message | default('Unknown error.') }}"
      when: item.status != 200
      loop: "{{ api_response.results }}"
      loop_control:
        loop_var: item
      
  # The 'always' block ensures logout happens regardless of success or failure.
  always:
    - name: Log out of IBM Cloud
      ansible.builtin.shell: |
        ibmcloud logout >/dev/null 2>&1
      changed_when: false
      failed_when: false
